apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calhack-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CalHacks23/calhacks23.git
    targetRevision: HEAD
    path: LLM_Ops
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    name: argo-workflows
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '0.29.2'
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
  labels:
    name: coder
spec:
  project: default
  source:
    repoURL: https://helm.coder.com/v2
    targetRevision: 0.23.5
    chart: coder 
    helm:
      values: |
        coder:
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "False"
          ingress:
            enable: true
            className: nginx
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: coder
