apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calhack-storage
  namespace: coder
spec:
  accessModes:
    - ReadWritOnce
  volumeMode: Filesystem
  storageClassName: default
  resources:
    requests:
      storage: 200Gi